In [1]:
from gym_tictactoe.env import TicTacToeEnv


env = TicTacToeEnv(size=5)

print("Available Actions:", env.available_actions())

actions = [0, 0, 6, 1, 9, 2, 10, 3, 8, 4]
for action in actions:
    observation, reward, done, trunc, _ = env.step(action)
    print(observation, reward, done)
    env.render()

    if done or trunc:
        print("Game Over!")
        break

print("Available Actions:", env.available_actions())


Available Actions: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]
[2. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0.] 0 False
  O| | | | 
  ----------
   | | | | 
  ----------
   | | | | 
  ----------
   | | | | 
  ----------
   | | | | 

[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0.] -2 False
  O| | | | 
  ----------
   | | | | 
  ----------
   | | | | 
  ----------
   | | | | 
  ----------
   | | | | 

[2. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0.] 0 False
  O| | | | 
  ----------
   |X| | | 
  ----------
   | | | | 
  ----------
   | | | | 
  ----------
   | | | | 

[1. 1. 0. 0. 0. 0. 2. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0.] 0 False
  O|O| | | 
  ----------
   |X| | | 
  ----------
   | | | | 
  ----------
   | | | | 
  ----------
   | | | | 

[2. 2. 0. 0. 0. 0. 1. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0.] 0 False
  O|O| 

In [1]:
import gymnasium as gym

from stable_baselines3 import DQN, DDPG, PPO
from gym_tictactoe.env import TicTacToeEnv
from stable_baselines3.common.logger import configure
from stable_baselines3.common.callbacks import EvalCallback

tmp_path = "log/"
# set up logger

env = TicTacToeEnv()
eval_callback = EvalCallback(env, best_model_save_path="ppomodel/",
                             log_path="logs/", eval_freq=1000,
                             deterministic=True, render=False, n_eval_episodes=100)


model = PPO("MlpPolicy", env, verbose=1)
model.learn(total_timesteps=100000, log_interval=1000, callback=eval_callback, progress_bar=True)
model.save("dqntictactoe")
new_logger = configure(tmp_path, ["stdout", "csv", "tensorboard"])
model.set_logger(new_logger)

del model # remove to demonstrate saving and loading

model = PPO.load("ppomodel/best_model.zip")

obs, info = env.reset()


done = False
obs, info = env.reset()
observation = obs
while not done:
    action, _states = model.predict(observation, deterministic=True)
    observation, reward, done, trunc, _ = env.step(action)
    print(observation, reward, done)
    env.render()

    if done or trunc:
        print("Game Over!")
        break

# while True:
#     action, _states = model.predict(obs, deterministic=True)
#     obs, reward, terminated, truncated, info = env.step(action)
#     if terminated or truncated:
#         obs, info = env.reset()

Output()

Using cuda device
Wrapping the env with a `Monitor` wrapper
Wrapping the env in a DummyVecEnv.


/home/frozenwolf/miniconda3/lib/python3.10/site-packages/stable_baselines3/common/evaluation.py:67: UserWarning: 
Evaluation environment is not wrapped with a ``Monitor`` wrapper. This may result in reporting modified episode 
lengths and rewards, if other wrappers happen to modify these. Consider wrapping environment first with ``Monitor``
wrapper.
  warnings.warn(

Eval num_timesteps=1000, episode_reward=-10.00 +/- 0.00

Episode length: 9.00 +/- 0.00

---------------------------------
| eval/              |          |
|    mean_ep_length  | 9        |
|    mean_reward     | -10      |
| time/              |          |
|    total_timesteps | 1000     |
---------------------------------


New best mean reward!

Eval num_timesteps=2000, episode_reward=-10.00 +/- 0.00

Episode length: 9.00 +/- 0.00

---------------------------------
| eval/              |          |
|    mean_ep_length  | 9        |
|    mean_reward     | -10      |
| time/              |          |
|    total_timesteps | 2000     |
---------------------------------


Eval num_timesteps=3000, episode_reward=-8.00 +/- 0.00

Episode length: 9.00 +/- 0.00

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 9           |
|    mean_reward          | -8          |
| time/                   |             |
|    total_timesteps      | 3000        |
| train/                  |             |
|    approx_kl            | 0.013579259 |
|    clip_fraction        | 0.135       |
|    clip_range           | 0.2         |
|    entropy_loss         | -2.19       |
|    explained_variance   | 0.0409      |
|    learning_rate        | 0.0003      |
|    loss                 | 2.19        |
|    n_updates            | 10          |
|    policy_gradient_loss | -0.0323     |
|    value_loss           | 6.67        |
-----------------------------------------


New best mean reward!

Eval num_timesteps=4000, episode_reward=-8.00 +/- 0.00

Episode length: 9.00 +/- 0.00

---------------------------------
| eval/              |          |
|    mean_ep_length  | 9        |
|    mean_reward     | -8       |
| time/              |          |
|    total_timesteps | 4000     |
---------------------------------


Eval num_timesteps=5000, episode_reward=1.00 +/- 0.00

Episode length: 5.00 +/- 0.00

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 5           |
|    mean_reward          | 1           |
| time/                   |             |
|    total_timesteps      | 5000        |
| train/                  |             |
|    approx_kl            | 0.015974171 |
|    clip_fraction        | 0.143       |
|    clip_range           | 0.2         |
|    entropy_loss         | -2.16       |
|    explained_variance   | 0.0497      |
|    learning_rate        | 0.0003      |
|    loss                 | 3.51        |
|    n_updates            | 20          |
|    policy_gradient_loss | -0.0306     |
|    value_loss           | 6.11        |
-----------------------------------------


New best mean reward!

Eval num_timesteps=6000, episode_reward=1.00 +/- 0.00

Episode length: 5.00 +/- 0.00

---------------------------------
| eval/              |          |
|    mean_ep_length  | 5        |
|    mean_reward     | 1        |
| time/              |          |
|    total_timesteps | 6000     |
---------------------------------


Eval num_timesteps=7000, episode_reward=1.00 +/- 0.00

Episode length: 7.00 +/- 2.00

----------------------------------------
| eval/                   |            |
|    mean_ep_length       | 7          |
|    mean_reward          | 1          |
| time/                   |            |
|    total_timesteps      | 7000       |
| train/                  |            |
|    approx_kl            | 0.01334921 |
|    clip_fraction        | 0.129      |
|    clip_range           | 0.2        |
|    entropy_loss         | -2.13      |
|    explained_variance   | -0.00381   |
|    learning_rate        | 0.0003     |
|    loss                 | 4.41       |
|    n_updates            | 30         |
|    policy_gradient_loss | -0.0294    |
|    value_loss           | 8.99       |
----------------------------------------


Eval num_timesteps=8000, episode_reward=1.00 +/- 0.00

Episode length: 7.00 +/- 2.00

---------------------------------
| eval/              |          |
|    mean_ep_length  | 7        |
|    mean_reward     | 1        |
| time/              |          |
|    total_timesteps | 8000     |
---------------------------------


Eval num_timesteps=9000, episode_reward=-1.00 +/- 0.00

Episode length: 8.00 +/- 0.00

----------------------------------------
| eval/                   |            |
|    mean_ep_length       | 8          |
|    mean_reward          | -1         |
| time/                   |            |
|    total_timesteps      | 9000       |
| train/                  |            |
|    approx_kl            | 0.01269167 |
|    clip_fraction        | 0.12       |
|    clip_range           | 0.2        |
|    entropy_loss         | -2.08      |
|    explained_variance   | -0.00941   |
|    learning_rate        | 0.0003     |
|    loss                 | 5.28       |
|    n_updates            | 40         |
|    policy_gradient_loss | -0.0291    |
|    value_loss           | 11.2       |
----------------------------------------


Eval num_timesteps=10000, episode_reward=-1.00 +/- 0.00

Episode length: 8.00 +/- 0.00

---------------------------------
| eval/              |          |
|    mean_ep_length  | 8        |
|    mean_reward     | -1       |
| time/              |          |
|    total_timesteps | 10000    |
---------------------------------


Eval num_timesteps=11000, episode_reward=-0.98 +/- 0.20

Episode length: 6.03 +/- 0.30

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 6.03        |
|    mean_reward          | -0.98       |
| time/                   |             |
|    total_timesteps      | 11000       |
| train/                  |             |
|    approx_kl            | 0.012310798 |
|    clip_fraction        | 0.121       |
|    clip_range           | 0.2         |
|    entropy_loss         | -2.04       |
|    explained_variance   | -0.0302     |
|    learning_rate        | 0.0003      |
|    loss                 | 5.23        |
|    n_updates            | 50          |
|    policy_gradient_loss | -0.0279     |
|    value_loss           | 10.1        |
-----------------------------------------


Eval num_timesteps=12000, episode_reward=-1.00 +/- 0.00

Episode length: 6.00 +/- 0.00

---------------------------------
| eval/              |          |
|    mean_ep_length  | 6        |
|    mean_reward     | -1       |
| time/              |          |
|    total_timesteps | 12000    |
---------------------------------


Eval num_timesteps=13000, episode_reward=-0.99 +/- 0.10

Episode length: 6.03 +/- 0.30

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 6.03        |
|    mean_reward          | -0.99       |
| time/                   |             |
|    total_timesteps      | 13000       |
| train/                  |             |
|    approx_kl            | 0.012109203 |
|    clip_fraction        | 0.131       |
|    clip_range           | 0.2         |
|    entropy_loss         | -1.99       |
|    explained_variance   | -0.0303     |
|    learning_rate        | 0.0003      |
|    loss                 | 4.55        |
|    n_updates            | 60          |
|    policy_gradient_loss | -0.0285     |
|    value_loss           | 9.05        |
-----------------------------------------


Eval num_timesteps=14000, episode_reward=-1.00 +/- 0.00

Episode length: 6.00 +/- 0.00

---------------------------------
| eval/              |          |
|    mean_ep_length  | 6        |
|    mean_reward     | -1       |
| time/              |          |
|    total_timesteps | 14000    |
---------------------------------


Eval num_timesteps=15000, episode_reward=0.50 +/- 0.50

Episode length: 9.00 +/- 0.00

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 9           |
|    mean_reward          | 0.5         |
| time/                   |             |
|    total_timesteps      | 15000       |
| train/                  |             |
|    approx_kl            | 0.012742937 |
|    clip_fraction        | 0.158       |
|    clip_range           | 0.2         |
|    entropy_loss         | -1.94       |
|    explained_variance   | -0.0103     |
|    learning_rate        | 0.0003      |
|    loss                 | 3.42        |
|    n_updates            | 70          |
|    policy_gradient_loss | -0.0312     |
|    value_loss           | 7.45        |
-----------------------------------------


Eval num_timesteps=16000, episode_reward=0.50 +/- 0.50

Episode length: 9.00 +/- 0.00

---------------------------------
| eval/              |          |
|    mean_ep_length  | 9        |
|    mean_reward     | 0.5      |
| time/              |          |
|    total_timesteps | 16000    |
---------------------------------


Eval num_timesteps=17000, episode_reward=-0.98 +/- 0.20

Episode length: 6.03 +/- 0.30

----------------------------------------
| eval/                   |            |
|    mean_ep_length       | 6.03       |
|    mean_reward          | -0.98      |
| time/                   |            |
|    total_timesteps      | 17000      |
| train/                  |            |
|    approx_kl            | 0.01290213 |
|    clip_fraction        | 0.131      |
|    clip_range           | 0.2        |
|    entropy_loss         | -1.88      |
|    explained_variance   | -0.0213    |
|    learning_rate        | 0.0003     |
|    loss                 | 3.1        |
|    n_updates            | 80         |
|    policy_gradient_loss | -0.0288    |
|    value_loss           | 5.72       |
----------------------------------------


Eval num_timesteps=18000, episode_reward=-1.00 +/- 0.00

Episode length: 6.00 +/- 0.00

---------------------------------
| eval/              |          |
|    mean_ep_length  | 6        |
|    mean_reward     | -1       |
| time/              |          |
|    total_timesteps | 18000    |
---------------------------------


Eval num_timesteps=19000, episode_reward=1.00 +/- 0.00

Episode length: 6.00 +/- 1.00

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 6           |
|    mean_reward          | 1           |
| time/                   |             |
|    total_timesteps      | 19000       |
| train/                  |             |
|    approx_kl            | 0.013098003 |
|    clip_fraction        | 0.149       |
|    clip_range           | 0.2         |
|    entropy_loss         | -1.83       |
|    explained_variance   | 0.00198     |
|    learning_rate        | 0.0003      |
|    loss                 | 2.19        |
|    n_updates            | 90          |
|    policy_gradient_loss | -0.0312     |
|    value_loss           | 3.84        |
-----------------------------------------


Eval num_timesteps=20000, episode_reward=1.00 +/- 0.00

Episode length: 6.00 +/- 1.00

---------------------------------
| eval/              |          |
|    mean_ep_length  | 6        |
|    mean_reward     | 1        |
| time/              |          |
|    total_timesteps | 20000    |
---------------------------------


Eval num_timesteps=21000, episode_reward=1.00 +/- 0.00

Episode length: 7.00 +/- 0.00

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 7           |
|    mean_reward          | 1           |
| time/                   |             |
|    total_timesteps      | 21000       |
| train/                  |             |
|    approx_kl            | 0.011761118 |
|    clip_fraction        | 0.137       |
|    clip_range           | 0.2         |
|    entropy_loss         | -1.79       |
|    explained_variance   | -0.0309     |
|    learning_rate        | 0.0003      |
|    loss                 | 1.79        |
|    n_updates            | 100         |
|    policy_gradient_loss | -0.029      |
|    value_loss           | 3.4         |
-----------------------------------------


Eval num_timesteps=22000, episode_reward=1.00 +/- 0.00

Episode length: 7.00 +/- 0.00

---------------------------------
| eval/              |          |
|    mean_ep_length  | 7        |
|    mean_reward     | 1        |
| time/              |          |
|    total_timesteps | 22000    |
---------------------------------


Eval num_timesteps=23000, episode_reward=-1.00 +/- 0.00

Episode length: 8.00 +/- 0.00

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 8           |
|    mean_reward          | -1          |
| time/                   |             |
|    total_timesteps      | 23000       |
| train/                  |             |
|    approx_kl            | 0.012702508 |
|    clip_fraction        | 0.146       |
|    clip_range           | 0.2         |
|    entropy_loss         | -1.75       |
|    explained_variance   | -0.0132     |
|    learning_rate        | 0.0003      |
|    loss                 | 1.22        |
|    n_updates            | 110         |
|    policy_gradient_loss | -0.0297     |
|    value_loss           | 2.79        |
-----------------------------------------


Eval num_timesteps=24000, episode_reward=-1.00 +/- 0.00

Episode length: 8.00 +/- 0.00

---------------------------------
| eval/              |          |
|    mean_ep_length  | 8        |
|    mean_reward     | -1       |
| time/              |          |
|    total_timesteps | 24000    |
---------------------------------


Eval num_timesteps=25000, episode_reward=0.50 +/- 0.50

Episode length: 8.00 +/- 1.00

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 8            |
|    mean_reward          | 0.5          |
| time/                   |              |
|    total_timesteps      | 25000        |
| train/                  |              |
|    approx_kl            | 0.0109295985 |
|    clip_fraction        | 0.123        |
|    clip_range           | 0.2          |
|    entropy_loss         | -1.72        |
|    explained_variance   | -0.0245      |
|    learning_rate        | 0.0003       |
|    loss                 | 1.28         |
|    n_updates            | 120          |
|    policy_gradient_loss | -0.0256      |
|    value_loss           | 2.41         |
------------------------------------------


Eval num_timesteps=26000, episode_reward=0.50 +/- 0.50

Episode length: 8.00 +/- 1.00

---------------------------------
| eval/              |          |
|    mean_ep_length  | 8        |
|    mean_reward     | 0.5      |
| time/              |          |
|    total_timesteps | 26000    |
---------------------------------


Eval num_timesteps=27000, episode_reward=-1.00 +/- 0.00

Episode length: 8.00 +/- 0.00

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 8           |
|    mean_reward          | -1          |
| time/                   |             |
|    total_timesteps      | 27000       |
| train/                  |             |
|    approx_kl            | 0.013144338 |
|    clip_fraction        | 0.161       |
|    clip_range           | 0.2         |
|    entropy_loss         | -1.68       |
|    explained_variance   | -0.0247     |
|    learning_rate        | 0.0003      |
|    loss                 | 0.838       |
|    n_updates            | 130         |
|    policy_gradient_loss | -0.0295     |
|    value_loss           | 1.78        |
-----------------------------------------


Eval num_timesteps=28000, episode_reward=-1.00 +/- 0.00

Episode length: 8.00 +/- 0.00

---------------------------------
| eval/              |          |
|    mean_ep_length  | 8        |
|    mean_reward     | -1       |
| time/              |          |
|    total_timesteps | 28000    |
---------------------------------


Eval num_timesteps=29000, episode_reward=0.50 +/- 0.50

Episode length: 7.00 +/- 2.00

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 7           |
|    mean_reward          | 0.5         |
| time/                   |             |
|    total_timesteps      | 29000       |
| train/                  |             |
|    approx_kl            | 0.011600098 |
|    clip_fraction        | 0.14        |
|    clip_range           | 0.2         |
|    entropy_loss         | -1.66       |
|    explained_variance   | -0.00215    |
|    learning_rate        | 0.0003      |
|    loss                 | 0.574       |
|    n_updates            | 140         |
|    policy_gradient_loss | -0.0283     |
|    value_loss           | 1.32        |
-----------------------------------------


Eval num_timesteps=30000, episode_reward=0.50 +/- 0.50

Episode length: 7.00 +/- 2.00

---------------------------------
| eval/              |          |
|    mean_ep_length  | 7        |
|    mean_reward     | 0.5      |
| time/              |          |
|    total_timesteps | 30000    |
---------------------------------


Eval num_timesteps=31000, episode_reward=0.50 +/- 0.50

Episode length: 7.00 +/- 2.00

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 7           |
|    mean_reward          | 0.5         |
| time/                   |             |
|    total_timesteps      | 31000       |
| train/                  |             |
|    approx_kl            | 0.011613859 |
|    clip_fraction        | 0.153       |
|    clip_range           | 0.2         |
|    entropy_loss         | -1.62       |
|    explained_variance   | -0.00865    |
|    learning_rate        | 0.0003      |
|    loss                 | 0.662       |
|    n_updates            | 150         |
|    policy_gradient_loss | -0.0295     |
|    value_loss           | 1.37        |
-----------------------------------------


Eval num_timesteps=32000, episode_reward=0.50 +/- 0.50

Episode length: 7.00 +/- 2.00

---------------------------------
| eval/              |          |
|    mean_ep_length  | 7        |
|    mean_reward     | 0.5      |
| time/              |          |
|    total_timesteps | 32000    |
---------------------------------


Eval num_timesteps=33000, episode_reward=0.50 +/- 0.50

Episode length: 8.00 +/- 1.00

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 8           |
|    mean_reward          | 0.5         |
| time/                   |             |
|    total_timesteps      | 33000       |
| train/                  |             |
|    approx_kl            | 0.010378996 |
|    clip_fraction        | 0.115       |
|    clip_range           | 0.2         |
|    entropy_loss         | -1.62       |
|    explained_variance   | -0.00528    |
|    learning_rate        | 0.0003      |
|    loss                 | 0.545       |
|    n_updates            | 160         |
|    policy_gradient_loss | -0.0241     |
|    value_loss           | 1.24        |
-----------------------------------------


Eval num_timesteps=34000, episode_reward=0.50 +/- 0.50

Episode length: 8.00 +/- 1.00

---------------------------------
| eval/              |          |
|    mean_ep_length  | 8        |
|    mean_reward     | 0.5      |
| time/              |          |
|    total_timesteps | 34000    |
---------------------------------


Eval num_timesteps=35000, episode_reward=1.00 +/- 0.00

Episode length: 7.00 +/- 2.00

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 7           |
|    mean_reward          | 1           |
| time/                   |             |
|    total_timesteps      | 35000       |
| train/                  |             |
|    approx_kl            | 0.010242677 |
|    clip_fraction        | 0.119       |
|    clip_range           | 0.2         |
|    entropy_loss         | -1.59       |
|    explained_variance   | -0.053      |
|    learning_rate        | 0.0003      |
|    loss                 | 0.57        |
|    n_updates            | 170         |
|    policy_gradient_loss | -0.0242     |
|    value_loss           | 1.17        |
-----------------------------------------


Eval num_timesteps=36000, episode_reward=1.00 +/- 0.00

Episode length: 7.00 +/- 2.00

---------------------------------
| eval/              |          |
|    mean_ep_length  | 7        |
|    mean_reward     | 1        |
| time/              |          |
|    total_timesteps | 36000    |
---------------------------------


Eval num_timesteps=37000, episode_reward=-1.00 +/- 0.00

Episode length: 8.00 +/- 0.00

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 8           |
|    mean_reward          | -1          |
| time/                   |             |
|    total_timesteps      | 37000       |
| train/                  |             |
|    approx_kl            | 0.011287142 |
|    clip_fraction        | 0.14        |
|    clip_range           | 0.2         |
|    entropy_loss         | -1.57       |
|    explained_variance   | -0.0603     |
|    learning_rate        | 0.0003      |
|    loss                 | 0.338       |
|    n_updates            | 180         |
|    policy_gradient_loss | -0.0257     |
|    value_loss           | 0.924       |
-----------------------------------------


Eval num_timesteps=38000, episode_reward=-1.00 +/- 0.00

Episode length: 8.00 +/- 0.00

---------------------------------
| eval/              |          |
|    mean_ep_length  | 8        |
|    mean_reward     | -1       |
| time/              |          |
|    total_timesteps | 38000    |
---------------------------------


Eval num_timesteps=39000, episode_reward=-1.00 +/- 0.00

Episode length: 8.00 +/- 0.00

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 8           |
|    mean_reward          | -1          |
| time/                   |             |
|    total_timesteps      | 39000       |
| train/                  |             |
|    approx_kl            | 0.011352103 |
|    clip_fraction        | 0.122       |
|    clip_range           | 0.2         |
|    entropy_loss         | -1.57       |
|    explained_variance   | -0.0317     |
|    learning_rate        | 0.0003      |
|    loss                 | 0.514       |
|    n_updates            | 190         |
|    policy_gradient_loss | -0.0234     |
|    value_loss           | 0.979       |
-----------------------------------------


Eval num_timesteps=40000, episode_reward=-1.00 +/- 0.00

Episode length: 8.00 +/- 0.00

---------------------------------
| eval/              |          |
|    mean_ep_length  | 8        |
|    mean_reward     | -1       |
| time/              |          |
|    total_timesteps | 40000    |
---------------------------------


Eval num_timesteps=41000, episode_reward=0.50 +/- 0.50

Episode length: 8.00 +/- 1.00

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 8           |
|    mean_reward          | 0.5         |
| time/                   |             |
|    total_timesteps      | 41000       |
| train/                  |             |
|    approx_kl            | 0.011805937 |
|    clip_fraction        | 0.137       |
|    clip_range           | 0.2         |
|    entropy_loss         | -1.54       |
|    explained_variance   | -0.00433    |
|    learning_rate        | 0.0003      |
|    loss                 | 0.496       |
|    n_updates            | 200         |
|    policy_gradient_loss | -0.0266     |
|    value_loss           | 0.945       |
-----------------------------------------


Eval num_timesteps=42000, episode_reward=0.50 +/- 0.50

Episode length: 8.00 +/- 1.00

---------------------------------
| eval/              |          |
|    mean_ep_length  | 8        |
|    mean_reward     | 0.5      |
| time/              |          |
|    total_timesteps | 42000    |
---------------------------------


Eval num_timesteps=43000, episode_reward=0.50 +/- 0.50

Episode length: 8.00 +/- 1.00

---------------------------------
| eval/              |          |
|    mean_ep_length  | 8        |
|    mean_reward     | 0.5      |
| time/              |          |
|    total_timesteps | 43000    |
---------------------------------


Eval num_timesteps=44000, episode_reward=1.00 +/- 0.00

Episode length: 7.00 +/- 0.00

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 7           |
|    mean_reward          | 1           |
| time/                   |             |
|    total_timesteps      | 44000       |
| train/                  |             |
|    approx_kl            | 0.011116964 |
|    clip_fraction        | 0.134       |
|    clip_range           | 0.2         |
|    entropy_loss         | -1.51       |
|    explained_variance   | -0.00719    |
|    learning_rate        | 0.0003      |
|    loss                 | 0.451       |
|    n_updates            | 210         |
|    policy_gradient_loss | -0.0248     |
|    value_loss           | 0.947       |
-----------------------------------------


Eval num_timesteps=45000, episode_reward=1.00 +/- 0.00

Episode length: 7.00 +/- 0.00

---------------------------------
| eval/              |          |
|    mean_ep_length  | 7        |
|    mean_reward     | 1        |
| time/              |          |
|    total_timesteps | 45000    |
---------------------------------


Eval num_timesteps=46000, episode_reward=1.00 +/- 0.00

Episode length: 7.00 +/- 0.00

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 7           |
|    mean_reward          | 1           |
| time/                   |             |
|    total_timesteps      | 46000       |
| train/                  |             |
|    approx_kl            | 0.012317646 |
|    clip_fraction        | 0.148       |
|    clip_range           | 0.2         |
|    entropy_loss         | -1.5        |
|    explained_variance   | -0.0237     |
|    learning_rate        | 0.0003      |
|    loss                 | 0.431       |
|    n_updates            | 220         |
|    policy_gradient_loss | -0.0267     |
|    value_loss           | 0.88        |
-----------------------------------------


Eval num_timesteps=47000, episode_reward=1.00 +/- 0.00

Episode length: 7.00 +/- 0.00

---------------------------------
| eval/              |          |
|    mean_ep_length  | 7        |
|    mean_reward     | 1        |
| time/              |          |
|    total_timesteps | 47000    |
---------------------------------


Eval num_timesteps=48000, episode_reward=1.00 +/- 0.00

Episode length: 7.00 +/- 0.00

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 7           |
|    mean_reward          | 1           |
| time/                   |             |
|    total_timesteps      | 48000       |
| train/                  |             |
|    approx_kl            | 0.012268484 |
|    clip_fraction        | 0.148       |
|    clip_range           | 0.2         |
|    entropy_loss         | -1.48       |
|    explained_variance   | -0.0241     |
|    learning_rate        | 0.0003      |
|    loss                 | 0.283       |
|    n_updates            | 230         |
|    policy_gradient_loss | -0.0256     |
|    value_loss           | 0.739       |
-----------------------------------------


Eval num_timesteps=49000, episode_reward=1.00 +/- 0.00

Episode length: 7.00 +/- 0.00

---------------------------------
| eval/              |          |
|    mean_ep_length  | 7        |
|    mean_reward     | 1        |
| time/              |          |
|    total_timesteps | 49000    |
---------------------------------


Eval num_timesteps=50000, episode_reward=-1.00 +/- 0.00

Episode length: 6.00 +/- 0.00

----------------------------------------
| eval/                   |            |
|    mean_ep_length       | 6          |
|    mean_reward          | -1         |
| time/                   |            |
|    total_timesteps      | 50000      |
| train/                  |            |
|    approx_kl            | 0.01091815 |
|    clip_fraction        | 0.122      |
|    clip_range           | 0.2        |
|    entropy_loss         | -1.45      |
|    explained_variance   | -0.0225    |
|    learning_rate        | 0.0003     |
|    loss                 | 0.28       |
|    n_updates            | 240        |
|    policy_gradient_loss | -0.0209    |
|    value_loss           | 0.666      |
----------------------------------------


Eval num_timesteps=51000, episode_reward=-1.00 +/- 0.00

Episode length: 6.00 +/- 0.00

---------------------------------
| eval/              |          |
|    mean_ep_length  | 6        |
|    mean_reward     | -1       |
| time/              |          |
|    total_timesteps | 51000    |
---------------------------------


Eval num_timesteps=52000, episode_reward=-1.00 +/- 0.00

Episode length: 6.00 +/- 0.00

---------------------------------------
| eval/                   |           |
|    mean_ep_length       | 6         |
|    mean_reward          | -1        |
| time/                   |           |
|    total_timesteps      | 52000     |
| train/                  |           |
|    approx_kl            | 0.0099595 |
|    clip_fraction        | 0.105     |
|    clip_range           | 0.2       |
|    entropy_loss         | -1.42     |
|    explained_variance   | -0.00985  |
|    learning_rate        | 0.0003    |
|    loss                 | 0.338     |
|    n_updates            | 250       |
|    policy_gradient_loss | -0.0221   |
|    value_loss           | 0.811     |
---------------------------------------


Eval num_timesteps=53000, episode_reward=-1.00 +/- 0.00

Episode length: 6.00 +/- 0.00

---------------------------------
| eval/              |          |
|    mean_ep_length  | 6        |
|    mean_reward     | -1       |
| time/              |          |
|    total_timesteps | 53000    |
---------------------------------


Eval num_timesteps=54000, episode_reward=-1.00 +/- 0.00

Episode length: 6.00 +/- 0.00

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 6           |
|    mean_reward          | -1          |
| time/                   |             |
|    total_timesteps      | 54000       |
| train/                  |             |
|    approx_kl            | 0.009728585 |
|    clip_fraction        | 0.126       |
|    clip_range           | 0.2         |
|    entropy_loss         | -1.42       |
|    explained_variance   | -0.00092    |
|    learning_rate        | 0.0003      |
|    loss                 | 0.356       |
|    n_updates            | 260         |
|    policy_gradient_loss | -0.0234     |
|    value_loss           | 0.702       |
-----------------------------------------


Eval num_timesteps=55000, episode_reward=-1.00 +/- 0.00

Episode length: 6.00 +/- 0.00

---------------------------------
| eval/              |          |
|    mean_ep_length  | 6        |
|    mean_reward     | -1       |
| time/              |          |
|    total_timesteps | 55000    |
---------------------------------


Eval num_timesteps=56000, episode_reward=-1.00 +/- 0.00

Episode length: 6.00 +/- 0.00

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 6            |
|    mean_reward          | -1           |
| time/                   |              |
|    total_timesteps      | 56000        |
| train/                  |              |
|    approx_kl            | 0.0116044935 |
|    clip_fraction        | 0.134        |
|    clip_range           | 0.2          |
|    entropy_loss         | -1.4         |
|    explained_variance   | 0.000273     |
|    learning_rate        | 0.0003       |
|    loss                 | 0.264        |
|    n_updates            | 270          |
|    policy_gradient_loss | -0.0235      |
|    value_loss           | 0.691        |
------------------------------------------


Eval num_timesteps=57000, episode_reward=-1.00 +/- 0.00

Episode length: 6.00 +/- 0.00

---------------------------------
| eval/              |          |
|    mean_ep_length  | 6        |
|    mean_reward     | -1       |
| time/              |          |
|    total_timesteps | 57000    |
---------------------------------


Eval num_timesteps=58000, episode_reward=1.00 +/- 0.00

Episode length: 7.00 +/- 0.00

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 7           |
|    mean_reward          | 1           |
| time/                   |             |
|    total_timesteps      | 58000       |
| train/                  |             |
|    approx_kl            | 0.008556138 |
|    clip_fraction        | 0.097       |
|    clip_range           | 0.2         |
|    entropy_loss         | -1.39       |
|    explained_variance   | -0.0151     |
|    learning_rate        | 0.0003      |
|    loss                 | 0.303       |
|    n_updates            | 280         |
|    policy_gradient_loss | -0.0199     |
|    value_loss           | 0.626       |
-----------------------------------------


Eval num_timesteps=59000, episode_reward=1.00 +/- 0.00

Episode length: 7.00 +/- 0.00

---------------------------------
| eval/              |          |
|    mean_ep_length  | 7        |
|    mean_reward     | 1        |
| time/              |          |
|    total_timesteps | 59000    |
---------------------------------


Eval num_timesteps=60000, episode_reward=-1.00 +/- 0.00

Episode length: 6.00 +/- 0.00

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 6           |
|    mean_reward          | -1          |
| time/                   |             |
|    total_timesteps      | 60000       |
| train/                  |             |
|    approx_kl            | 0.011980871 |
|    clip_fraction        | 0.141       |
|    clip_range           | 0.2         |
|    entropy_loss         | -1.35       |
|    explained_variance   | -0.0276     |
|    learning_rate        | 0.0003      |
|    loss                 | 0.332       |
|    n_updates            | 290         |
|    policy_gradient_loss | -0.0256     |
|    value_loss           | 0.697       |
-----------------------------------------


Eval num_timesteps=61000, episode_reward=-1.00 +/- 0.00

Episode length: 6.00 +/- 0.00

---------------------------------
| eval/              |          |
|    mean_ep_length  | 6        |
|    mean_reward     | -1       |
| time/              |          |
|    total_timesteps | 61000    |
---------------------------------


Eval num_timesteps=62000, episode_reward=-1.00 +/- 0.00

Episode length: 8.00 +/- 0.00

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 8           |
|    mean_reward          | -1          |
| time/                   |             |
|    total_timesteps      | 62000       |
| train/                  |             |
|    approx_kl            | 0.009967817 |
|    clip_fraction        | 0.119       |
|    clip_range           | 0.2         |
|    entropy_loss         | -1.34       |
|    explained_variance   | -0.0255     |
|    learning_rate        | 0.0003      |
|    loss                 | 0.274       |
|    n_updates            | 300         |
|    policy_gradient_loss | -0.023      |
|    value_loss           | 0.618       |
-----------------------------------------


Eval num_timesteps=63000, episode_reward=-1.00 +/- 0.00

Episode length: 8.00 +/- 0.00

---------------------------------
| eval/              |          |
|    mean_ep_length  | 8        |
|    mean_reward     | -1       |
| time/              |          |
|    total_timesteps | 63000    |
---------------------------------


Eval num_timesteps=64000, episode_reward=0.50 +/- 0.50

Episode length: 8.00 +/- 1.00

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 8           |
|    mean_reward          | 0.5         |
| time/                   |             |
|    total_timesteps      | 64000       |
| train/                  |             |
|    approx_kl            | 0.011043141 |
|    clip_fraction        | 0.122       |
|    clip_range           | 0.2         |
|    entropy_loss         | -1.3        |
|    explained_variance   | -0.00848    |
|    learning_rate        | 0.0003      |
|    loss                 | 0.216       |
|    n_updates            | 310         |
|    policy_gradient_loss | -0.0225     |
|    value_loss           | 0.566       |
-----------------------------------------


Eval num_timesteps=65000, episode_reward=0.50 +/- 0.50

Episode length: 8.00 +/- 1.00

---------------------------------
| eval/              |          |
|    mean_ep_length  | 8        |
|    mean_reward     | 0.5      |
| time/              |          |
|    total_timesteps | 65000    |
---------------------------------


Eval num_timesteps=66000, episode_reward=1.00 +/- 0.00

Episode length: 7.00 +/- 0.00

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 7           |
|    mean_reward          | 1           |
| time/                   |             |
|    total_timesteps      | 66000       |
| train/                  |             |
|    approx_kl            | 0.010418262 |
|    clip_fraction        | 0.136       |
|    clip_range           | 0.2         |
|    entropy_loss         | -1.26       |
|    explained_variance   | 0.014       |
|    learning_rate        | 0.0003      |
|    loss                 | 0.239       |
|    n_updates            | 320         |
|    policy_gradient_loss | -0.0254     |
|    value_loss           | 0.678       |
-----------------------------------------


Eval num_timesteps=67000, episode_reward=1.00 +/- 0.00

Episode length: 7.00 +/- 0.00

---------------------------------
| eval/              |          |
|    mean_ep_length  | 7        |
|    mean_reward     | 1        |
| time/              |          |
|    total_timesteps | 67000    |
---------------------------------


Eval num_timesteps=68000, episode_reward=1.00 +/- 0.00

Episode length: 7.00 +/- 0.00

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 7           |
|    mean_reward          | 1           |
| time/                   |             |
|    total_timesteps      | 68000       |
| train/                  |             |
|    approx_kl            | 0.009852946 |
|    clip_fraction        | 0.122       |
|    clip_range           | 0.2         |
|    entropy_loss         | -1.2        |
|    explained_variance   | 0.00614     |
|    learning_rate        | 0.0003      |
|    loss                 | 0.292       |
|    n_updates            | 330         |
|    policy_gradient_loss | -0.0229     |
|    value_loss           | 0.694       |
-----------------------------------------


Eval num_timesteps=69000, episode_reward=1.00 +/- 0.00

Episode length: 7.00 +/- 0.00

---------------------------------
| eval/              |          |
|    mean_ep_length  | 7        |
|    mean_reward     | 1        |
| time/              |          |
|    total_timesteps | 69000    |
---------------------------------


Eval num_timesteps=70000, episode_reward=1.00 +/- 0.00

Episode length: 7.00 +/- 0.00

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 7           |
|    mean_reward          | 1           |
| time/                   |             |
|    total_timesteps      | 70000       |
| train/                  |             |
|    approx_kl            | 0.009882722 |
|    clip_fraction        | 0.112       |
|    clip_range           | 0.2         |
|    entropy_loss         | -1.17       |
|    explained_variance   | -0.00216    |
|    learning_rate        | 0.0003      |
|    loss                 | 0.397       |
|    n_updates            | 340         |
|    policy_gradient_loss | -0.0218     |
|    value_loss           | 0.685       |
-----------------------------------------


Eval num_timesteps=71000, episode_reward=1.00 +/- 0.00

Episode length: 7.00 +/- 0.00

---------------------------------
| eval/              |          |
|    mean_ep_length  | 7        |
|    mean_reward     | 1        |
| time/              |          |
|    total_timesteps | 71000    |
---------------------------------


Eval num_timesteps=72000, episode_reward=1.00 +/- 0.00

Episode length: 7.00 +/- 0.00

----------------------------------------
| eval/                   |            |
|    mean_ep_length       | 7          |
|    mean_reward          | 1          |
| time/                   |            |
|    total_timesteps      | 72000      |
| train/                  |            |
|    approx_kl            | 0.01083228 |
|    clip_fraction        | 0.128      |
|    clip_range           | 0.2        |
|    entropy_loss         | -1.14      |
|    explained_variance   | -0.00785   |
|    learning_rate        | 0.0003     |
|    loss                 | 0.229      |
|    n_updates            | 350        |
|    policy_gradient_loss | -0.0225    |
|    value_loss           | 0.525      |
----------------------------------------


Eval num_timesteps=73000, episode_reward=1.00 +/- 0.00

Episode length: 7.00 +/- 0.00

---------------------------------
| eval/              |          |
|    mean_ep_length  | 7        |
|    mean_reward     | 1        |
| time/              |          |
|    total_timesteps | 73000    |
---------------------------------


Eval num_timesteps=74000, episode_reward=1.00 +/- 0.00

Episode length: 7.00 +/- 0.00

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 7           |
|    mean_reward          | 1           |
| time/                   |             |
|    total_timesteps      | 74000       |
| train/                  |             |
|    approx_kl            | 0.009277297 |
|    clip_fraction        | 0.102       |
|    clip_range           | 0.2         |
|    entropy_loss         | -1.1        |
|    explained_variance   | 0.0171      |
|    learning_rate        | 0.0003      |
|    loss                 | 0.266       |
|    n_updates            | 360         |
|    policy_gradient_loss | -0.0226     |
|    value_loss           | 0.536       |
-----------------------------------------


Eval num_timesteps=75000, episode_reward=1.00 +/- 0.00

Episode length: 7.00 +/- 0.00

---------------------------------
| eval/              |          |
|    mean_ep_length  | 7        |
|    mean_reward     | 1        |
| time/              |          |
|    total_timesteps | 75000    |
---------------------------------


Eval num_timesteps=76000, episode_reward=1.00 +/- 0.00

Episode length: 7.00 +/- 0.00

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 7           |
|    mean_reward          | 1           |
| time/                   |             |
|    total_timesteps      | 76000       |
| train/                  |             |
|    approx_kl            | 0.009602832 |
|    clip_fraction        | 0.104       |
|    clip_range           | 0.2         |
|    entropy_loss         | -1.09       |
|    explained_variance   | 0.00887     |
|    learning_rate        | 0.0003      |
|    loss                 | 0.175       |
|    n_updates            | 370         |
|    policy_gradient_loss | -0.0199     |
|    value_loss           | 0.559       |
-----------------------------------------


Eval num_timesteps=77000, episode_reward=1.00 +/- 0.00

Episode length: 7.00 +/- 0.00

---------------------------------
| eval/              |          |
|    mean_ep_length  | 7        |
|    mean_reward     | 1        |
| time/              |          |
|    total_timesteps | 77000    |
---------------------------------


Eval num_timesteps=78000, episode_reward=1.00 +/- 0.00

Episode length: 7.00 +/- 0.00

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 7           |
|    mean_reward          | 1           |
| time/                   |             |
|    total_timesteps      | 78000       |
| train/                  |             |
|    approx_kl            | 0.010662788 |
|    clip_fraction        | 0.109       |
|    clip_range           | 0.2         |
|    entropy_loss         | -1.05       |
|    explained_variance   | 0.00585     |
|    learning_rate        | 0.0003      |
|    loss                 | 0.223       |
|    n_updates            | 380         |
|    policy_gradient_loss | -0.0212     |
|    value_loss           | 0.485       |
-----------------------------------------


Eval num_timesteps=79000, episode_reward=1.00 +/- 0.00

Episode length: 7.00 +/- 0.00

---------------------------------
| eval/              |          |
|    mean_ep_length  | 7        |
|    mean_reward     | 1        |
| time/              |          |
|    total_timesteps | 79000    |
---------------------------------


Eval num_timesteps=80000, episode_reward=1.00 +/- 0.00

Episode length: 7.00 +/- 0.00

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 7           |
|    mean_reward          | 1           |
| time/                   |             |
|    total_timesteps      | 80000       |
| train/                  |             |
|    approx_kl            | 0.010497207 |
|    clip_fraction        | 0.113       |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.994      |
|    explained_variance   | 0.00789     |
|    learning_rate        | 0.0003      |
|    loss                 | 0.195       |
|    n_updates            | 390         |
|    policy_gradient_loss | -0.0212     |
|    value_loss           | 0.495       |
-----------------------------------------


Eval num_timesteps=81000, episode_reward=1.00 +/- 0.00

Episode length: 7.00 +/- 0.00

---------------------------------
| eval/              |          |
|    mean_ep_length  | 7        |
|    mean_reward     | 1        |
| time/              |          |
|    total_timesteps | 81000    |
---------------------------------


Eval num_timesteps=82000, episode_reward=1.00 +/- 0.00

Episode length: 7.00 +/- 0.00

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 7           |
|    mean_reward          | 1           |
| time/                   |             |
|    total_timesteps      | 82000       |
| train/                  |             |
|    approx_kl            | 0.010738451 |
|    clip_fraction        | 0.122       |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.966      |
|    explained_variance   | 0.0614      |
|    learning_rate        | 0.0003      |
|    loss                 | 0.158       |
|    n_updates            | 400         |
|    policy_gradient_loss | -0.0236     |
|    value_loss           | 0.416       |
-----------------------------------------


Eval num_timesteps=83000, episode_reward=1.00 +/- 0.00

Episode length: 7.00 +/- 0.00

---------------------------------
| eval/              |          |
|    mean_ep_length  | 7        |
|    mean_reward     | 1        |
| time/              |          |
|    total_timesteps | 83000    |
---------------------------------


Eval num_timesteps=84000, episode_reward=1.00 +/- 0.00

Episode length: 7.00 +/- 0.00

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 7           |
|    mean_reward          | 1           |
| time/                   |             |
|    total_timesteps      | 84000       |
| train/                  |             |
|    approx_kl            | 0.010563198 |
|    clip_fraction        | 0.115       |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.908      |
|    explained_variance   | 0.0535      |
|    learning_rate        | 0.0003      |
|    loss                 | 0.133       |
|    n_updates            | 410         |
|    policy_gradient_loss | -0.0227     |
|    value_loss           | 0.385       |
-----------------------------------------


Eval num_timesteps=85000, episode_reward=1.00 +/- 0.00

Episode length: 7.00 +/- 0.00

---------------------------------
| eval/              |          |
|    mean_ep_length  | 7        |
|    mean_reward     | 1        |
| time/              |          |
|    total_timesteps | 85000    |
---------------------------------


Eval num_timesteps=86000, episode_reward=1.00 +/- 0.00

Episode length: 7.00 +/- 0.00

---------------------------------
| eval/              |          |
|    mean_ep_length  | 7        |
|    mean_reward     | 1        |
| time/              |          |
|    total_timesteps | 86000    |
---------------------------------


Eval num_timesteps=87000, episode_reward=1.00 +/- 0.00

Episode length: 7.00 +/- 0.00

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 7           |
|    mean_reward          | 1           |
| time/                   |             |
|    total_timesteps      | 87000       |
| train/                  |             |
|    approx_kl            | 0.011296572 |
|    clip_fraction        | 0.113       |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.866      |
|    explained_variance   | 0.024       |
|    learning_rate        | 0.0003      |
|    loss                 | 0.0967      |
|    n_updates            | 420         |
|    policy_gradient_loss | -0.0209     |
|    value_loss           | 0.319       |
-----------------------------------------


Eval num_timesteps=88000, episode_reward=1.00 +/- 0.00

Episode length: 7.00 +/- 0.00

---------------------------------
| eval/              |          |
|    mean_ep_length  | 7        |
|    mean_reward     | 1        |
| time/              |          |
|    total_timesteps | 88000    |
---------------------------------


Eval num_timesteps=89000, episode_reward=1.00 +/- 0.00

Episode length: 7.00 +/- 0.00

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 7           |
|    mean_reward          | 1           |
| time/                   |             |
|    total_timesteps      | 89000       |
| train/                  |             |
|    approx_kl            | 0.009134476 |
|    clip_fraction        | 0.112       |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.806      |
|    explained_variance   | 0.0672      |
|    learning_rate        | 0.0003      |
|    loss                 | 0.216       |
|    n_updates            | 430         |
|    policy_gradient_loss | -0.0224     |
|    value_loss           | 0.398       |
-----------------------------------------


Eval num_timesteps=90000, episode_reward=1.00 +/- 0.00

Episode length: 7.00 +/- 0.00

---------------------------------
| eval/              |          |
|    mean_ep_length  | 7        |
|    mean_reward     | 1        |
| time/              |          |
|    total_timesteps | 90000    |
---------------------------------


Eval num_timesteps=91000, episode_reward=1.00 +/- 0.00

Episode length: 7.00 +/- 0.00

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 7           |
|    mean_reward          | 1           |
| time/                   |             |
|    total_timesteps      | 91000       |
| train/                  |             |
|    approx_kl            | 0.008637939 |
|    clip_fraction        | 0.118       |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.77       |
|    explained_variance   | 0.0261      |
|    learning_rate        | 0.0003      |
|    loss                 | 0.141       |
|    n_updates            | 440         |
|    policy_gradient_loss | -0.0197     |
|    value_loss           | 0.308       |
-----------------------------------------


Eval num_timesteps=92000, episode_reward=1.00 +/- 0.00

Episode length: 7.00 +/- 0.00

---------------------------------
| eval/              |          |
|    mean_ep_length  | 7        |
|    mean_reward     | 1        |
| time/              |          |
|    total_timesteps | 92000    |
---------------------------------


Eval num_timesteps=93000, episode_reward=1.00 +/- 0.00

Episode length: 7.00 +/- 0.00

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 7           |
|    mean_reward          | 1           |
| time/                   |             |
|    total_timesteps      | 93000       |
| train/                  |             |
|    approx_kl            | 0.006528319 |
|    clip_fraction        | 0.0833      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.725      |
|    explained_variance   | 0.0724      |
|    learning_rate        | 0.0003      |
|    loss                 | 0.191       |
|    n_updates            | 450         |
|    policy_gradient_loss | -0.0187     |
|    value_loss           | 0.238       |
-----------------------------------------


Eval num_timesteps=94000, episode_reward=1.00 +/- 0.00

Episode length: 7.00 +/- 0.00

---------------------------------
| eval/              |          |
|    mean_ep_length  | 7        |
|    mean_reward     | 1        |
| time/              |          |
|    total_timesteps | 94000    |
---------------------------------


Eval num_timesteps=95000, episode_reward=1.00 +/- 0.00

Episode length: 7.00 +/- 0.00

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 7           |
|    mean_reward          | 1           |
| time/                   |             |
|    total_timesteps      | 95000       |
| train/                  |             |
|    approx_kl            | 0.010039566 |
|    clip_fraction        | 0.119       |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.701      |
|    explained_variance   | 0.0799      |
|    learning_rate        | 0.0003      |
|    loss                 | 0.0136      |
|    n_updates            | 460         |
|    policy_gradient_loss | -0.0216     |
|    value_loss           | 0.166       |
-----------------------------------------


Eval num_timesteps=96000, episode_reward=1.00 +/- 0.00

Episode length: 7.00 +/- 0.00

---------------------------------
| eval/              |          |
|    mean_ep_length  | 7        |
|    mean_reward     | 1        |
| time/              |          |
|    total_timesteps | 96000    |
---------------------------------


Eval num_timesteps=97000, episode_reward=1.00 +/- 0.00

Episode length: 7.00 +/- 0.00

---------------------------------------
| eval/                   |           |
|    mean_ep_length       | 7         |
|    mean_reward          | 1         |
| time/                   |           |
|    total_timesteps      | 97000     |
| train/                  |           |
|    approx_kl            | 0.0095461 |
|    clip_fraction        | 0.0892    |
|    clip_range           | 0.2       |
|    entropy_loss         | -0.66     |
|    explained_variance   | 0.0412    |
|    learning_rate        | 0.0003    |
|    loss                 | 0.116     |
|    n_updates            | 470       |
|    policy_gradient_loss | -0.0192   |
|    value_loss           | 0.27      |
---------------------------------------


Eval num_timesteps=98000, episode_reward=1.00 +/- 0.00

Episode length: 7.00 +/- 0.00

---------------------------------
| eval/              |          |
|    mean_ep_length  | 7        |
|    mean_reward     | 1        |
| time/              |          |
|    total_timesteps | 98000    |
---------------------------------


Eval num_timesteps=99000, episode_reward=1.00 +/- 0.00

Episode length: 7.00 +/- 0.00

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 7           |
|    mean_reward          | 1           |
| time/                   |             |
|    total_timesteps      | 99000       |
| train/                  |             |
|    approx_kl            | 0.008188137 |
|    clip_fraction        | 0.0865      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.605      |
|    explained_variance   | 0.0486      |
|    learning_rate        | 0.0003      |
|    loss                 | 0.0712      |
|    n_updates            | 480         |
|    policy_gradient_loss | -0.0206     |
|    value_loss           | 0.19        |
-----------------------------------------


Eval num_timesteps=100000, episode_reward=1.00 +/- 0.00

Episode length: 7.00 +/- 0.00

---------------------------------
| eval/              |          |
|    mean_ep_length  | 7        |
|    mean_reward     | 1        |
| time/              |          |
|    total_timesteps | 100000   |
---------------------------------


Logging to log/
[0. 0. 0. 0. 0. 0. 0. 1. 0.] 0 False
   | | 
  ------
   | | 
  ------
   |O| 
[0. 0. 0. 0. 0. 0. 0. 2. 0.] -2 False
   | | 
  ------
   | | 
  ------
   |O| 
[0. 0. 0. 0. 0. 0. 0. 1. 0.] -2 False
   | | 
  ------
   | | 
  ------
   |O| 
[0. 0. 0. 0. 0. 0. 0. 2. 0.] -2 False
   | | 
  ------
   | | 
  ------
   |O| 
[0. 0. 0. 0. 0. 0. 0. 1. 0.] -2 False
   | | 
  ------
   | | 
  ------
   |O| 
[0. 0. 0. 0. 0. 0. 0. 2. 0.] -2 False
   | | 
  ------
   | | 
  ------
   |O| 
[0. 0. 0. 0. 0. 0. 0. 1. 0.] -2 False
   | | 
  ------
   | | 
  ------
   |O| 
[0. 0. 0. 0. 0. 0. 0. 2. 0.] -2 False
   | | 
  ------
   | | 
  ------
   |O| 
[0. 0. 0. 0. 0. 0. 0. 1. 0.] -2 False
   | | 
  ------
   | | 
  ------
   |O| 
Game Over!


In [11]:
action

array([0])

In [14]:
import numpy as np
model = PPO.load("ppomodel/best_model.zip")


done = False
obs, info = env.reset()

altter = True
observation = obs
while not done:
    print(observation)
    if altter:
        action = np.asarray(int(input("Enter action: ")))
        
    else:
        action, _states = model.predict(observation, deterministic=True)
    observation, reward, done, trunc, _ = env.step(action)
    altter = not altter
    # print(observation, reward, done)
    print(reward, done, trunc)
    env.render()

    if done or trunc:
        print("Game Over!")
        break

[0. 0. 0. 0. 0. 0. 0. 0. 0.]


0 False False
   |O| 
  ------
   | | 
  ------
   | | 
[0. 2. 0. 0. 0. 0. 0. 0. 0.]
0 False False
   |O| 
  ------
   | | 
  ------
   | |X
[0. 1. 0. 0. 0. 0. 0. 0. 2.]
0 False False
   |O| 
  ------
  O| | 
  ------
   | |X
[0. 2. 0. 2. 0. 0. 0. 0. 1.]
0 False False
  X|O| 
  ------
  O| | 
  ------
   | |X
[2. 1. 0. 1. 0. 0. 0. 0. 2.]
0 False False
  X|O| 
  ------
  O|O| 
  ------
   | |X
[1. 2. 0. 2. 2. 0. 0. 0. 1.]
0 False False
  X|O| 
  ------
  O|O| 
  ------
   |X|X
[2. 1. 0. 1. 1. 0. 0. 2. 2.]
0 False False
  X|O| 
  ------
  O|O| 
  ------
  O|X|X
[1. 2. 0. 2. 2. 0. 2. 1. 1.]
0 False False
  X|O|X
  ------
  O|O| 
  ------
  O|X|X
[2. 1. 2. 1. 1. 0. 1. 2. 2.]


ValueError: invalid literal for int() with base 10: ''